services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      MOCK_INFERENCE: "true"
      DATABASE_URL: sqlite:///./data/mit_system.db
    volumes:
      - ./data:/app/data
      - ./backend/uploads:/app/uploads
      - ./ml/artifacts:/app/ml/artifacts

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
